spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: prajay
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false

  h2:
    console.enabled: true
server:
  port: 5000